import type { LovelaceCardConfig } from "../../../data/lovelace/config/card";
import "../cards/hui-entity-card";
import "../cards/hui-entities-card";
import "../cards/hui-button-card";
import "../cards/hui-entity-button-card";
import "../cards/hui-glance-card";
import "../cards/hui-grid-card";
import "../cards/hui-light-card";
import "../cards/hui-sensor-card";
import "../cards/hui-thermostat-card";
import "../cards/hui-weather-forecast-card";
import "../cards/hui-tile-card";
import "../cards/hui-heading-card";
export declare const tryCreateCardElement: (config: LovelaceCardConfig) => import("../types").LovelaceCard;
export declare const createCardElement: (config: LovelaceCardConfig) => import("../types").LovelaceCard;
export declare const getCardElementClass: (type: string) => Promise<import("../types").LovelaceCardConstructor>;
