import type { PropertyValues, TemplateResult } from "lit";
import { LitElement, nothing } from "lit";
import "../../../../components/ha-automation-row";
import "../../../../components/ha-card";
import "../../../../components/ha-expansion-panel";
import "../../../../components/ha-icon-button";
import "../../../../components/ha-md-button-menu";
import "../../../../components/ha-md-divider";
import "../../../../components/ha-md-menu-item";
import "../../../../components/ha-service-icon";
import "../../../../components/ha-tooltip";
import type { AutomationClipboard } from "../../../../data/automation";
import type { EntityRegistryEntry } from "../../../../data/entity_registry";
import type { FloorRegistryEntry } from "../../../../data/floor_registry";
import type { LabelRegistryEntry } from "../../../../data/label_registry";
import type { Action } from "../../../../data/script";
import type { HomeAssistant } from "../../../../types";
import "../ha-automation-editor-warning";
import "./ha-automation-action-editor";
import "./types/ha-automation-action-choose";
import "./types/ha-automation-action-condition";
import "./types/ha-automation-action-delay";
import "./types/ha-automation-action-device_id";
import "./types/ha-automation-action-event";
import "./types/ha-automation-action-if";
import "./types/ha-automation-action-parallel";
import "./types/ha-automation-action-sequence";
import "./types/ha-automation-action-service";
import "./types/ha-automation-action-set_conversation_response";
import "./types/ha-automation-action-stop";
import "./types/ha-automation-action-wait_for_trigger";
import "./types/ha-automation-action-wait_template";
export declare const getAutomationActionType: import("memoize-one").MemoizedFn<(action: Action | undefined) => "repeat" | "stop" | "action" | "sequence" | "event" | "service" | "device_id" | "parallel" | "delay" | "wait_template" | "wait_for_trigger" | "choose" | "if" | "variables" | "set_conversation_response" | "condition" | "play_media" | "repeat_count" | "repeat_while" | "repeat_until" | "repeat_for_each">;
export interface ActionElement extends LitElement {
    action: Action;
    expandAll?: () => void;
    collapseAll?: () => void;
}
export declare const handleChangeEvent: (element: ActionElement, ev: CustomEvent) => void;
export default class HaAutomationActionRow extends LitElement {
    hass: HomeAssistant;
    action: Action;
    narrow: boolean;
    disabled: boolean;
    root: boolean;
    first?: boolean;
    last?: boolean;
    highlight?: boolean;
    optionsInSidebar: boolean;
    sortSelected: boolean;
    _clipboard?: AutomationClipboard;
    _entityReg: EntityRegistryEntry[];
    _labelReg: LabelRegistryEntry[];
    _floorReg: Record<string, FloorRegistryEntry>;
    private _uiModeAvailable;
    private _yamlMode;
    private _selected;
    private _collapsed;
    private _warnings?;
    private _actionEditor?;
    private _automationRowElement?;
    get selected(): boolean;
    protected firstUpdated(changedProperties: PropertyValues): void;
    protected willUpdate(changedProperties: PropertyValues): void;
    private _renderOverflowLabel;
    private _renderRow;
    protected render(): TemplateResult<1> | typeof nothing;
    private _onValueChange;
    private _setClipboard;
    private _onDisable;
    private _runAction;
    private _onDelete;
    private _switchUiMode;
    private _switchYamlMode;
    private _renameAction;
    private _duplicateAction;
    private _insertAfter;
    private _copyAction;
    private _cutAction;
    private _moveUp;
    private _moveDown;
    private _toggleYamlMode;
    private _handleUiModeNotAvailable;
    private _toggleSidebar;
    openSidebar(action?: Action): void;
    expand(): void;
    collapse(): void;
    expandAll(): void;
    collapseAll(): void;
    private _uiSupported;
    private _toggleCollapse;
    focus(): void;
    static styles: import("lit").CSSResult[];
}
declare global {
    interface HTMLElementTagNameMap {
        "ha-automation-action-row": HaAutomationActionRow;
    }
}
