import type { HassEntities } from "home-assistant-js-websocket";
import type { LocalizeFunc } from "../../../common/translations/localize";
import type { AreasDisplayValue } from "../../../components/ha-areas-display-editor";
import type { EnergyPreferences } from "../../../data/energy";
import type { LovelaceBadgeConfig } from "../../../data/lovelace/config/badge";
import type { LovelaceCardConfig } from "../../../data/lovelace/config/card";
import type { LovelaceSectionConfig } from "../../../data/lovelace/config/section";
import type { LovelaceViewConfig } from "../../../data/lovelace/config/view";
import type { HomeAssistant } from "../../../types";
import type { EntitiesCardConfig } from "../cards/types";
export declare const computeSection: (entityIds: string[], sectionOptions?: Partial<LovelaceSectionConfig>) => LovelaceSectionConfig;
export declare const computeCards: (hass: HomeAssistant, entityIds: string[], entityCardOptions: Partial<EntitiesCardConfig>, renderFooterEntities?: boolean) => LovelaceCardConfig[];
export declare const computeBadges: (_states: HassEntities, entityIds: string[]) => LovelaceBadgeConfig[];
export declare const generateViewConfig: (hass: HomeAssistant, path: string, title: string | undefined, icon: string | undefined, entities: HassEntities) => LovelaceViewConfig;
export declare const generateDefaultViewConfig: (hass: HomeAssistant, localize: LocalizeFunc, energyPrefs?: EnergyPreferences, areasPrefs?: AreasDisplayValue, hideEntitiesWithoutAreas?: boolean, hideEnergy?: boolean) => LovelaceViewConfig;
