import type { LovelaceBadgeConfig } from "../../../data/lovelace/config/badge";
import type { LovelaceCardConfig } from "../../../data/lovelace/config/card";
import type { LovelaceSectionRawConfig } from "../../../data/lovelace/config/section";
import type { LovelaceConfig } from "../../../data/lovelace/config/types";
import type { LovelaceViewConfig } from "../../../data/lovelace/config/view";
import type { HomeAssistant } from "../../../types";
import type { LovelaceCardPath, LovelaceContainerPath } from "./lovelace-path";
export declare const addCard: (config: LovelaceConfig, path: LovelaceContainerPath, cardConfig: LovelaceCardConfig) => LovelaceConfig;
export declare const addCards: (config: LovelaceConfig, path: LovelaceContainerPath, cardConfigs: LovelaceCardConfig[]) => LovelaceConfig;
export declare const replaceCard: (config: LovelaceConfig, path: LovelaceCardPath, cardConfig: LovelaceCardConfig) => LovelaceConfig;
export declare const deleteCard: (config: LovelaceConfig, path: LovelaceCardPath) => LovelaceConfig;
export declare const insertCard: (config: LovelaceConfig, path: LovelaceCardPath, cardConfig: LovelaceCardConfig) => LovelaceConfig;
export declare const moveCardToIndex: (config: LovelaceConfig, path: LovelaceCardPath, index: number) => LovelaceConfig;
export declare const moveCardToContainer: (config: LovelaceConfig, fromPath: LovelaceCardPath, toPath: LovelaceContainerPath) => LovelaceConfig;
export declare const moveCard: (config: LovelaceConfig, fromPath: LovelaceCardPath, toPath: LovelaceCardPath) => LovelaceConfig;
export declare const addView: (hass: HomeAssistant, config: LovelaceConfig, viewConfig: LovelaceViewConfig, tolerantPath?: boolean) => LovelaceConfig;
export declare const replaceView: (hass: HomeAssistant, config: LovelaceConfig, viewIndex: number, viewConfig: LovelaceViewConfig) => LovelaceConfig;
export declare const swapView: (config: LovelaceConfig, path1: number, path2: number) => LovelaceConfig;
export declare const deleteView: (config: LovelaceConfig, viewIndex: number) => LovelaceConfig;
export declare const moveViewToDashboard: (hass: HomeAssistant, fromConfig: LovelaceConfig, toConfig: LovelaceConfig, viewIndex: number) => [LovelaceConfig, LovelaceConfig];
export declare const addSection: (config: LovelaceConfig, viewIndex: number, sectionConfig: LovelaceSectionRawConfig) => LovelaceConfig;
export declare const deleteSection: (config: LovelaceConfig, viewIndex: number, sectionIndex: number) => LovelaceConfig;
export declare const insertSection: (config: LovelaceConfig, viewIndex: number, sectionIndex: number, sectionConfig: LovelaceSectionRawConfig) => LovelaceConfig;
export declare const moveSection: (config: LovelaceConfig, fromPath: [number, number], toPath: [number, number]) => LovelaceConfig;
export declare const addBadge: (config: LovelaceConfig, path: LovelaceContainerPath, badgeConfig: LovelaceBadgeConfig) => LovelaceConfig;
export declare const addBadges: (config: LovelaceConfig, path: LovelaceContainerPath, badgeConfig: LovelaceBadgeConfig[]) => LovelaceConfig;
export declare const replaceBadge: (config: LovelaceConfig, path: LovelaceCardPath, cardConfig: LovelaceBadgeConfig) => LovelaceConfig;
export declare const deleteBadge: (config: LovelaceConfig, path: LovelaceCardPath) => LovelaceConfig;
export declare const insertBadge: (config: LovelaceConfig, path: LovelaceCardPath, badgeConfig: LovelaceBadgeConfig) => LovelaceConfig;
export declare const moveBadge: (config: LovelaceConfig, fromPath: LovelaceCardPath, toPath: LovelaceCardPath) => LovelaceConfig;
