name: HACS validation

on:
  workflow_call:

jobs:
  validate:
    name: Validate HACS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Go Hass Cards Artifact
        uses: actions/download-artifact@v4
        with:
          name: Go Hass Cards
          path: dist

      - name: List files
        run: |
          ls -la
          ls -la dist

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: plugin
