name: HACS validation

on:
  workflow_call:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    name: Validate HACS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: plugin
